### ISSUE TITLE
Missing "execute if data storage"

### ISSUE THREAD

**Issue by Tetrajak** [jan00bl/mcfunction-novum#12]
Suggestions provided after typing "execute if data" only have "entity" and "block", but not "storage".

For reference, "storage" is a valid source of data for "execute if data", as documented on [the MC wiki](https://minecraft.gamepedia.com/Commands/execute#.28if.7Cunless.29_data).

Also wanted to add that I'm really enjoying this package, keep up the good work!

**Comment by jan00bl** [comment]
Thank you ^^
