### ISSUE TITLE
Missing Coloring in the Tellraw Command 

### ISSUE THREAD

**Issue by pbflo** [jan00bl/mcfunction-novum#13]
The coloring for the tellraw command ends after some time:
![Screenshot 2020-11-15 155454](https://user-images.githubusercontent.com/56795244/99188272-70a06880-275b-11eb-8ecd-bcdd59b3b8a8.png)
the full two commands seen in the picture [examples.txt](https://github.com/jan00bl/mcfunction-novum/files/5542588/examples.txt)

**Comment by jan00bl** [comment]
This behaviour is not a bug. It is a result of atom's token limit. You can increase the token limit with this pack:
https://github.com/postcasio/atom-grammar-token-limit
But keep in mind increasing the token limit can impact performance
