### ISSUE TITLE
No netherite item ids

### ISSUE THREAD

**Issue by Readf0x** [jan00bl/mcfunction-novum#16]
![screen](https://user-images.githubusercontent.com/57838054/99284665-27542580-27fc-11eb-8c0e-76c2373a880d.png)

**Comment by Readf0x** [comment]
I now realize the item ids are not being saved in the syntax :P

**Comment by jan00bl** [comment]
hey, its because you are in snapshot mode and the /replaceitem command was replaced with /item.
You can change the version in the package settings ^^

**Comment by Readf0x** [comment]
Alright, cool, thanks!

>
