### ISSUE TITLE
Syntax highlighting issue with NBT

### ISSUE THREAD

**Issue by Tetrajak** [jan00bl/mcfunction-novum#20]
I'm not entirely sure what causes it, but every so often the highlighting on NBT will continue the current colour until the end of the line. It's a little subtle in the attached image, but everything after "Tags:[" is highlighted lime green (although it doesn't continue on to the next line after a line break).
![image](https://user-images.githubusercontent.com/12091037/100147865-ce257980-2f00-11eb-8d98-ce97cb9b821c.png)

**Comment by jan00bl** [comment]
You can find an explanation for this behavior in the README.md.

**Comment by Tetrajak** [comment]
Thank you, I missed that!
