### ISSUE TITLE
Highlighting on double-prefixed comments is wrong

### ISSUE THREAD

**Issue by CreeperMagnet** [jan00bl/mcfunction-novum#21]
<img width="515" alt="Screen Shot 2020-11-25 at 3 59 28 PM" src="https://user-images.githubusercontent.com/45321954/100285933-68a0af80-2f37-11eb-873d-9666e5e516b7.png">

"#" Highlights as gray italics
"##+" Highlights as purple

This is different from the previous package you've forked from, in which both were highlighted correctly as dark gray in italics.

**Comment by jan00bl** [comment]
I added this purple highlighting on purpose. I use it to comment out commands. But I could try to add an option to disable it
