### ISSUE TITLE
Syntax Highlighting Problem

### ISSUE THREAD

**Issue by MrSlimeOfSlime** [jan00bl/mcfunction-novum#38]
![image](https://user-images.githubusercontent.com/58266694/119039235-dcf96000-b968-11eb-9ed3-962904fcd44a.png)
idk why but this causes problems, yes, the functions called are valid, its a valid command, just not highlighted correctly

**Comment by jan00bl** [comment]
duplicate from #37

**Comment by anonymous123-code** [comment]
Looks like token limit @jan00bl  (starts with `@e` -> cutted)

**Comment by jan00bl** [comment]
Oh yeah true, I just saw a highlighting error in a selector. I'm now really curious how you hit the token limit in a selector. How long is this command? @anonymous123-code

**Comment by anonymous123-code** [comment]
Its an execute command... They can get really long
