### ISSUE TITLE
Keyword highlighting in comments

### ISSUE THREAD

**Issue by Scroogeee** [jan00bl/mcfunction-novum#57]
mcfunction keywords (like "clear", "at", "in" etc.) should not be highlighted in comments, because it may cause confusion.

**Comment by Scroogeee** [comment]
<img width="457" alt="Bildschirmfoto 2023-08-11 um 17 14 55" src="https://github.com/jan00bl/mcfunction-novum/assets/30441849/61081ac3-bfae-41fc-a8ee-19b781ed9e88">

**Comment by sertonix** [comment]
The setting "Enable Comment Out Highlighting" toggles this behaviour.

**Comment by Scroogeee** [comment]
Sorry, I should have found that setting prior to asking. For me it seems strange that it is on by default though.
